[project]
name = "shared"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools>=3.11.0",
    "boto3>=1.38.8",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]

[tool.uv]
package = true
